Please accept our final PR.
marsiitr/DumE pull request #5
Opened 2021-08-08 14:12 UTC by rodion0917

2021-08-08 15:08 UTC, theobscuredev requested changes
Hi @rodion0917 & team,
Nice work so far, although changes are required!

1. Update the README according to the changes suggested below.
2. Create a section named 'Software Aspect' after 'Workflow' and elaborate the tech stack and your algorithms. Preferably, create one more README inside src and hyperlink it in your actual README. This new file will contain a detailed explanation of your code and logic which is currently not so obvious. Refer this for more info: https://github.com/marsiitr/RoverSim#software-aspects
3. Wherever mentioned, update Matlab to 'MATLAB'.
4. Create a subfolder "MATLAB" under the folder "DumE/Simulation" and shift the contents of "DumE/Simulation" into "DumE/Simulation/MATLAB". Add "DumE/Simulation/README.md" and elaborate on simulation.
5. Create a subsection "Simulation" in "DumE/README.md" and give a summary and reference of "DumE/Simulation/README.md" in that.
For points 4 and 5, refer to [RoverSim Documentation](https://github.com/marsiitr/RoverSim). Also, mention the instructions to replicate your simulation there. 

Lemme know once you make these changes and make sure you tag me (@) in this thread.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +Open Projects 2021
Apply header by using: ## Open Projects 2021

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +</p>
Apply proper alignment. Make sure the image & it's title is center aligned EVERYWHERE.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +***
Justify the entire text using the `<p>` paragraph tag and `justify` attribute. Make sure you justify all the paragraphs separately. For eg:
`<p align="justify">`
  `<h2>Abstract</h2>`
  `<p>A Rube Goldberg Machine is .........................</p>`
`</p>`

Refer this README for the same: https://raw.githubusercontent.com/marsiitr/RoverSim/main/README.md

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +<i>Workflow</i>
Center align the title. The `<i>` tag is outside the `<p>` tag hence the attributes won't be applied to the later.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +<i>Placiing the object</i>
Review the entire README again for such grammatical errors.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +| *Total*                           | *4,09,400*  |
Hyperlink the proof for each of these prices. And add a note after the table mentioning that these are the annual prices referred from the official MATHWORKS site.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +Dum-E is a perfect robotic arm for performing simple tasks in factory settings. It can also be used in household for any kind of pick up and place tasks.
Elaborate the applications. There are lots of use cases of robotic arms. Mention a few of them including the features of your model and how it can be extended to real-life scenario.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +***
Avoid informal tone. Elaborate what do you mean by 'Can't function in dynamic environment?'. Use bullet points if required to specify the points.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +In future, we would work on making Dum-E function in a dynamic environment. Also, we try to enable Dum-E as a whole and not just its end-effector to move in dynamic environment.
Elaborate more on the future scope. Precisely mention the features you wish to add in the future and if possible hyperlink the feature from official Mathworks docs.

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +4.[Siddhant Shekhar](https://github.com/SiddhantShekhar) <br/>
Leave proper space after the bullet points for aesthetic purposes only. Refer this README: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +[Pick and Place Workflow using Stateflow](https://in.mathworks.com/help/robotics/ug/pick-and-place-workflow-using-stateflow.html)
Use bullet points. Refer this README: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md And wherever present, capitalize all the characters in 'MATLAB' instead of 'Matlab'

2021-08-08 15:08 UTC, theobscuredev commented on README.md
> +
Add a section named 'Software Aspect' after 'Workflow'. And hyperlink a README file by creating it inside src folder where you'll explain the code and algorithm. Refer this: https://github.com/marsiitr/RoverSim#software-aspects

2021-08-11 17:35 UTC, SanjeevKrishnan approved these changes
Good work team!
PR looks fine. Merging the PR

2021-08-11 17:35 UTC, merged